version: "3"

networks:
  gitea:
    external: false

services:
  server:
    image: gitea/gitea:latest
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: always
    networks:
      - gitea
    volumes:
      - ./gitea:/data
    ports:
      - "3000:3000"
      - "222:22"
  bob:
    image: peter/bob:latest
    container_name: bob
    restart: always
    networks: 
      - gitea
    volumes:
      - ./bob:/opt/bob/data
    ports:
      - "8080:8080"
    